const adventures = [
    "Draw a self-portrait on a napkin or scrap paper.",
    "Walk backwards for 1 minute (carefully!).",
    "Call a relative just to say hi.",
    "Do 10 jumping jacks and 5 pushups.",
    "Find an object in the room and write a 3-sentence backstory for it.",
    "Go outside and take a photo of a flower or interesting texture.",
    "Listen to a song from a genre you usually dislike.",
    "Meditate for 5 minutes focusing only on your breath.",
    "Write a haiku about your current mood.",
    "Declutter one small drawer or shelf.",
    "Learn to say 'Hello' in 3 new languages.",
    "Make a cup of tea or coffee and drink it without doing anything else.",
    "Stand on one leg for as long as you can (switch legs).",
    "Look out the window and count how many red things you see.",
    "Read a random Wikipedia article.",
    "Doodle a monster using your non-dominant hand.",
    "Send a compliment to a friend via text.",
    "Stretch your arms and touch your toes for 2 minutes.",
    "Try to juggle with 2 (or 3) small objects.",
    "Write down 3 things you are grateful for today.",
    "Hum your favorite song and record it.",
    "Clean the screen of your phone and computer.",
    "Organize the apps on your phone home screen.",
    "Find a new word in the dictionary and use it in a sentence.",
    "Close your eyes and listen to the furthest sound you can hear.",
    "Make a paper airplane and fly it.",
    "Do a quick 5-minute yoga flow.",
    "Write a letter to your future self (seal it!).",
    "Watch a funny cat video.",
    "Eat a piece of fruit slowly, savoring every bite.",
    "Rearrange the items on your desk.",
    "Find 5 things that are blue in your surroundings.",
    "Practice your signature 10 times.",
    "Whistle a tune.",
    "Do a plank for as long as you can.",
    "Look up the history of your street name.",
    "Make a list of places you want to visit.",
    "Sketch the view from your window.",
    "Massage your hands and fingers.",
    "Create a new playlist with 5 happy songs.",
    "Google 'fun facts about [your favorite animal]'.",
    "Try to touch your nose with your tongue.",
    "Write a short poem about coffee or tea.",
    "Plan your dream breakfast for tomorrow.",
    "Count to 100 in a foreign language (look up the numbers if needed).",
    "Find a quote that inspires you and write it down.",
    "Take 10 deep breaths.",
    "Water your plants (or find a plant to water).",
    "Dance to one song like nobody is watching.",
    "Smile at yourself in the mirror for 30 seconds."
];
